version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - music-library-network
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 5555:5555
    command: npm run start
    depends_on:
      - db
    restart: always
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    networks:
      - music-library-network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - initdb:/docker-entrypoint-initdb.d
    restart: always

networks:
  music-library-network:
    driver: bridge

volumes:
  pgdata:
  initdb:
